# Generated by Django 3.1.5 on 2021-03-05 20:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000, null=True)),
                ('title', models.CharField(max_length=252, null=True)),
                ('modules', models.JSONField(blank=True, default=app.models.default_module, null=True)),
                ('images', models.JSONField(blank=True, default=dict, null=True)),
                ('examples', models.JSONField(blank=True, default=dict, null=True)),
                ('definitions', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
