# Generated by Django 3.1.5 on 2021-04-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='text',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='text',
            name='images',
        ),
        migrations.AddField(
            model_name='text',
            name='word_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
