# Generated by Django 3.1.5 on 2021-04-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=252, null=True)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
