# Generated by Django 3.1.5 on 2021-02-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='modules',
            field=models.JSONField(blank=True, default={'anagrams': {'adjective': False, 'adverb': False, 'noun': False, 'verb': False}, 'flashcards': {'adjective': False, 'adverb': False, 'noun': False, 'verb': False}, 'quiz': {'conjugations': False}}, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
