# Generated by Django 3.1.5 on 2021-01-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='images',
            field=models.JSONField(blank=True, default={'test': 'test'}, null=True),
        ),
    ]
