# Generated by Django 3.1.5 on 2021-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
