# Generated by Django 3.1.5 on 2021-02-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210204_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='content',
        ),
    ]
