# Generated by Django 3.1.5 on 2021-01-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210128_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
