# Generated by Django 3.1.5 on 2021-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210129_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='definitions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='examples',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
